// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace KemblaJoggers
{
	public partial class scanButton : UIViewController
	{
		public scanButton (IntPtr handle) : base (handle)
		{
		}
	}
}
